outOfBandManagers:
  - name: OA-1
    oobm:
      oobmAddress: 192.168.9.9
      oobmUser: Administrator
      oobmPassword: Administrator1@
      oobmType: oa


physicalHosts:
  - id: 34333638-3234-4D32-3237-343530305235
    oobm:
      manager: OA-1
      oobmExtra:
        bay: 1
    hostname: controlhost1
    portProfile: HPE_C7000_GEN10_NONRED
    hostProfile: control_mdm_sds
    cluster: openstack
    serviceProfiles:
      - sds_pd1
      - write_only_log_generator
      - cee_logrotate
  - id: 35393050-3432-4D32-3230-33393034324E
    oobm:
      manager: OA-1
      oobmExtra:
        bay: 2  
    hostname: controlhost2
    portProfile: HPE_C7000_GEN10_NONRED
    hostProfile: control_mdm_gw_sds
    cluster: openstack
    serviceProfiles:
      - sds_pd1
      - write_only_log_generator
      - cee_logrotate
  - id: 34333638-3234-4D32-3239-323130323859
    oobm:
      manager: OA-1
      oobmExtra:
        bay: 3  # 1-16
    hostname: controlhost3
    portProfile: HPE_C7000_GEN10_NONRED
    hostProfile: control_mdm_gw_sds
    cluster: openstack
    serviceProfiles:
      - sds_pd1
      - write_only_log_generator
      - cee_logrotate
###||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
###|||||||||||||||||||||||||||||||||||COMPUTES|||||||||||||||||||||||||||||||||||
###||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||

  - id: 34333638-3234-5A43-3230-323330364734
    oobm:
      manager: OA-1
      oobmExtra:
        bay: 4  # 1-16
    hostname: computehost4
    portProfile: HPE_C7000_GEN10_NONRED
    hostProfile: compute_sds_tb
    cluster: openstack
    serviceProfiles:
      - sds_pd1
      - write_only_log_generator
      - cee_logrotate      
  - id: 34333638-3234-4D32-3237-343530305235
    oobm:
      manager: OA-1
      oobmExtra:
        bay: 5  # 1-16
    hostname: computehost5
    portProfile: HPE_C7000_GEN10_NONRED
    hostProfile: compute_sds_tb
    cluster: openstack
    serviceProfiles:
      - sds_pd1
      - write_only_log_generator
      - cee_logrotate 
  - id: 34333638-3234-4D32-3239-32313032384E
    oobm:
      manager: OA-1
      oobmExtra:
        bay: 6  # 1-16
    hostname: computehost6
    portProfile: HPE_C7000_GEN10_NONRED
    hostProfile: compute
    cluster: openstack
    serviceProfiles:
      - sds_pd1
      - write_only_log_generator
      - cee_logrotate      
  - id: 34333638-3234-4D32-3239-313630335151
    oobm:
      manager: OA-1
      oobmExtra:
        bay: 7  # 1-16
    hostname: computehost7
    portProfile: HPE_C7000_GEN10_NONRED
    hostProfile: compute
    cluster: openstack
    serviceProfiles:
      - write_only_log_generator
      - cee_logrotate 
  - id: 34333638-3234-4D32-3237-34353030504A
    oobm:
      manager: OA-1
      oobmExtra:
        bay: 8  # 1-16
    hostname: computehost8
    portProfile: HPE_C7000_GEN10_NONRED
    hostProfile: compute
    cluster: openstack
    serviceProfiles:
      - write_only_log_generator
      - cee_logrotate 
  # - id: 34333638-3234-4D32-3238-323030355138
    # oobm:
      # manager: OA-1
      # oobmExtra:
        # bay: 9  # 1-16
    # hostname: computehost9
    # portProfile: HPE_C7000_GEN10_NONRED
    # hostProfile: compute
    # cluster: openstack
    # serviceProfiles:
      # - write_only_log_generator
      # - cee_logrotate 
  # - id: 35393050-3432-4D32-3239-34333036484C
    # oobm:
      # manager: OA-1
      # oobmExtra:
        # bay: 12  # 1-16
    # hostname: computehost10
    # portProfile: HPE_C7000_GEN10_NONRED
    # hostProfile: 
    # cluster: openstack
    # serviceProfiles:
      # - write_only_log_generator
      # - cee_logrotate 
      
virtualHosts:
  - hostname: infra1
    hypervisor: controlhost1
    portProfile: VIRTUAL_INFRA
    hostProfile: infra
    cluster: infra
    serviceProfiles:
      - write_only_log_aggregator
      - cee_logrotate
  - hostname: infra2
    hypervisor: controlhost2
    portProfile: VIRTUAL_INFRA
    hostProfile: infra
    cluster: infra
    serviceProfiles:
     - write_only_log_aggregator
     - cee_logrotate
  - hostname: infra3
    hypervisor: controlhost3
    portProfile: VIRTUAL_INFRA
    hostProfile: infra
    cluster: infra
    serviceProfiles:
      - write_only_log_aggregator
      - cee_logrotate
#  - hostname: csc1
#    hypervisor: controlhost1
#    portProfile: VIRTUAL_CSC
#    hostProfile: csc
#    cluster: csc
#    serviceProfiles:
#      - write_only_log_generator
#      - cee_logrotate
#  - hostname: csc2
#    hypervisor: controlhost2
#    portProfile: VIRTUAL_CSC
#    hostProfile: csc
#    cluster: csc
#    serviceProfiles:
#      - write_only_log_generator
#      - cee_logrotate
#  - hostname: csc3
#    hypervisor: controlhost3
#    portProfile: VIRTUAL_CSC
#    hostProfile: csc
#    cluster: csc
#    serviceProfiles:
#      - write_only_log_generator
#      - cee_logrotate
#  - hostname: networkhost1
#    hypervisor: controlhost1
#    portProfile: VIRTUAL_NETWORK
#    hostProfile: vnetwork
#    cluster: openstack
#    serviceProfiles:
#      - write_only_log_generator
#      - cee_logrotate
#  - hostname: networkhost2
#    hypervisor: controlhost2
#    portProfile: VIRTUAL_NETWORK
#    hostProfile: vnetwork
#    cluster: openstack
#    serviceProfiles:
#      - write_only_log_generator
#      - cee_logrotate
#  - hostname: networkhost3
#    hypervisor: controlhost3
#    portProfile: VIRTUAL_NETWORK
#    hostProfile: vnetwork
#    cluster: openstack
#    serviceProfiles:
#      - write_only_log_generator
#      - cee_logrotate
...
